import fs from "node:fs";
import type { Evidence } from "../schemas/evidence.schema.js";

export interface CIEnvironment {
  isCI: boolean;
  provider: "github" | "gitlab" | "jenkins" | "unknown";
  runId?: string;
}

/** Detect CI environment from environment variables */
export function detectCI(): CIEnvironment {
  if (process.env.GITHUB_ACTIONS === "true") {
    return { isCI: true, provider: "github", runId: process.env.GITHUB_RUN_ID };
  }
  if (process.env.GITLAB_CI === "true") {
    return { isCI: true, provider: "gitlab", runId: process.env.CI_PIPELINE_ID };
  }
  if (process.env.JENKINS_URL) {
    return { isCI: true, provider: "jenkins", runId: process.env.BUILD_NUMBER };
  }
  if (process.env.CI === "true") {
    return { isCI: true, provider: "unknown" };
  }
  return { isCI: false, provider: "unknown" };
}

/** Write a GitHub Actions step summary (markdown) from evidence */
export function generateGitHubActionsSummary(evidence: Evidence): void {
  const summaryPath = process.env.GITHUB_STEP_SUMMARY;
  if (!summaryPath) return;

  const statusIcon =
    evidence.status === "success" ? "✅" : evidence.status === "fail" ? "❌" : "⚠️";
  const lines = [
    `## ${statusIcon} fwai Run: ${evidence.run_id}`,
    "",
    `| Field | Value |`,
    `|-------|-------|`,
    `| Status | ${evidence.status} |`,
    `| Duration | ${evidence.duration_ms}ms |`,
    `| Tools | ${evidence.tools.length} |`,
    `| Skill | ${evidence.skill ?? "N/A"} |`,
    `| MCU | ${evidence.project.target_mcu} |`,
  ];

  if (evidence.llm?.estimated_cost_usd) {
    lines.push(`| LLM Cost | $${evidence.llm.estimated_cost_usd.toFixed(4)} |`);
  }
  if (evidence.sbom) {
    lines.push(`| SBOM | ${evidence.sbom.components_count} components |`);
  }
  if (evidence.signature) {
    lines.push(`| Signed | ${evidence.signature.algorithm} |`);
  }

  lines.push("", `> Generated by fwai v${evidence.client_version ?? "0.1.0"}`);

  fs.appendFileSync(summaryPath, lines.join("\n") + "\n");
}

/** Generate a markdown badge for CI status */
export function formatCIBadge(status: string): string {
  const color = status === "success" ? "brightgreen" : status === "fail" ? "red" : "yellow";
  return `![fwai](https://img.shields.io/badge/fwai-${encodeURIComponent(status)}-${color})`;
}
